### ISSUE TITLE
Mehrere Server und Load Balancing

### ISSUE THREAD

**Issue by MHajoha** [questionpy-org/moodle-qtype_questionpy#35]
Zwei use cases wollen wir im Plugin erlauben:
* Verschiedene Server: Die Konfiguration mehrerer Server, die verschiedene Pakete anbieten. Bei der Suche werden die verfügbaren Pakete aller Server zusammen aufgelistet. Dabei könnte angezeigt werden, woher die Pakete kommen, abgesehen davon sollte der Lehrende allerdings keinen Unterschied zwischen den Servern sehen, sondern lediglich zwischen Paketen wählen.
* Load Balancing: Die Konfiguration mehrerer Server, die die gleichen Pakete anbieten. Hier werden API-Calls zwischen den Servern verteilt (z.B. mit Round-Robin). Unter der Annahme, dass die Server sich gleich verhalten, sollte es keinen funktionalen Unterschied für Lehrende oder Studis geben.

Wir wollen beides erlauben, also verschiedene Server-Gruppen (z.B. `tu`, `hu`, `firma-xy`), die jeweils 1 oder mehr Server enthalten, die die gleichen Pakete anbieten.

**Todo**
* [ ] Verwalten von Server-Sets (der Name kann gern ein anderer sein) auf der Admin-Seite des Plugins
  * Ein Server-Set sollte durch einen kurzen Namen identifiziert werden, und enthält 1 oder mehr Server-URLs
    * TBD: Sollen Passwort und Timeout pro Server-Set oder pro Server konfiguriert werden?
* [ ] Bei der Suche die Pakete von jedem Server-Set holen und anzeigen
  * Pro Set nur einmal, da innerhalb eines Sets alle Server the gleichen Pakete anbieten sollen
  * Hier schon gerne einen Server zufällig oder per Round Robin aussuchen
  * Idealerweise alle Server-Sets parallel
  * Sollten zwei Server-Sets dasselbe Paket anbieten, gewinnt das, welches in der Config weiter oben steht.
  * TBD: Die Antwort ein paar Minuten cachen?
  * TBD: Anzeigen, aus welchem Set das Paket stammt?
* [ ] Bei Erstellen einer Frage den Namen des Server-Sets abspeichern, aus dem das Paket stammt
  * TBD: In der `qtype_questionpy`-Tabelle oder in der `qtype_questionpy_package`-Tabelle?
* [ ] Bei QPPE-Calls an das Paket einen Server aus dem entsprechenden Set wählen
