### ISSUE TITLE
Epic: User Interface für Trainer/Admins

### ISSUE THREAD

**Issue by janbritz** [questionpy-org/moodle-qtype_questionpy#36]
# UI - Roadmap

### Wiederverwendbare QPy-Paket-Auswahl-Komponenten
- Gemeinsamkeiten:
    - [x] Optionen können angezeigt werden (mit drei Punkte-Menü) (#53)
          - (Ent-)Favorisieren des Pakets 
          - Website aufrufen
          - Lizenz des Pakets anzeigen
    - [ ] Anzeige des Icon
    - [x] Unterteilung der Pakete in Kategorien
          - Alle Pakete
          - Zuletzt verwendet
          - Favoriten
          - Mein Pakete
    - [x] (Ent-)Favorisieren des Pakets  (#97)
    - [x] Sortierfunktion nach (#88)
          - Name
          - zuletzt hinzugefügt Datum
    - [x] (klappbare) Anzeige des Beschreibungstext
          - einfache Lösung mit ...
          - dynamische Anpassung Abschnitts (Seitenbreite)
    - [x] Anzeige von Tags (#114)
    - [x] Auswahl und Filter von/mit Tags (#114)
    - [ ] Meine Pakete Sonderheiten:
          - Download
          - Löschung

- Unterschiede:
    1. Frageerstellung: Übersicht aller QPy-Pakete
        - [x] Anzeige und Auswahl aller verfügbaren Versionen eines Pakets (#53)
        - [x] Markierung bei lokalen Paketen
        - [x] Paket ist auswählbar und lädt zugehörige Form nach (#53)
        - [x] #102
        - [x] Nach dem Hochladen:
              - Wechsel in "Meine"-Tab
              - Umstellung des Sortierfilters auf "Zuletzt hinzugefügt"

    2. Frageerstellung / -bearbeitung: nach Auswahl eines QPy-Pakets
        - [x] Möglichkeit das Paket zu wechseln (#53)
        - [ ] Warnung und Option auf Aktualisierung bei veralteten Paketen

    3. Admin: Übersicht aller QPy-Pakete
        - [ ] Löschen bestimmter Pakete und bestimmter Versionen
        - [x] Eigenes Paket hochladen
              - Kontext-Auswahl
              - Nicht im "Meine"-Tab anzeigen
              - Statt "Meine" -> "Hochgeladene"

### Weiteres
- [x] Frageerstellung: Pakete sollen aus der Datenbank geladen werden und nicht direkt vom Server
- [ ] Auslagerung der Paketverwaltung auf eine eigene Seite (und nicht in den Settings)
