### ISSUE TITLE
Epic: Fragen-UI

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/moodle-qtype_questionpy#52]
Issues:

- [QPy-URLs / Dateien in Fragen einbinden](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=43750788)
- [CSS-Unterstützung](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=35568349)
- [Fragen-UI XSD](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=35595067)
- [Fragen-UI dokumentieren](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=35594971)
- [Aufteilung in Subquestions](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=43736806)
- [Popovers & Modals (`qpy:display`)](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=43739719)
- [Dateien in Antworten hochladen (`qpy:file-upload`)](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=43736449)
- [Custom Validation Messages](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=43734097)
- [Python-Funktion zum Parsen von Kommazahlen](https://github.com/orgs/questionpy-org/projects/2/views/1?pane=issue&itemId=43479489)

PRs:

- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/49>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/56>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/59>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/61>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/64>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/65>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/66>
- <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/67>

TBD:

- Attribut `qpy:use="scoring-explanation"`, wie in QTI?
  - Erlaubte Werte: instructions, scoring-instructions, scoring-explanation, info, debug
- Kennzeichnung, ob ein Eingabefeld korrekt beantwortet wurde, wie viele Punkte, max. Punktzahl

**Comment by MHajoha** [comment]
Ich habe mal versucht, das in größtenteils tabellarische Form zu gießen: <https://tefen.isis.tu-berlin.de/wiki/doku.php?id=questionpy:question_ui>

Wenn ich mit questionpy-org/moodle-qtype_questionpy#46 durch bin, werde ich denke ich die Sachen einbauen, die wenig Diskussionsbedarf haben:

* [x] `disabled` bei read-only. (Bisher nur `input`-Tags)
* [x] Name und id mangling (inkl. Referenzen darauf)
* [x] Auflösung von Platzhaltern
* [x] Entschärfung von `<button type="submit">`
* [x] `qpy:if-role`
* [x] Ersetzung von `pattern` und `required` durch "softe" Validierung: https://github.com/questionpy-org/moodle-qtype_questionpy/issues/57
  * [ ] `qpy:if-invalid`
  * [ ] `qpy:if-required-field-empty`
